In [1]:
# Install NLTK
!pip install nltk pandas -q

# Import required libraries
import nltk
import pandas as pd

# Download required NLTK resources
nltk.download('wordnet')
nltk.download('omw-1.4')

print("NLTK resources downloaded successfully!")

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

NLTK resources downloaded successfully!

In [2]:
from nltk.corpus import wordnet as wn

# Select 10 English words
words = [
    "car",
    "bank",
    "bat",
    "dog",
    "light",
    "plant",
    "book",
    "teacher",
    "student",
    "computer"
]

print("Selected words:")
print(words)

Selected words:
['car', 'bank', 'bat', 'dog', 'light', 'plant', 'book', 'teacher', 'student', 'computer']

In [3]:
# Display synsets, definitions and examples for each word

for word in words:
    print("\n" + "=" * 60)
    print("WORD:", word)
    print("=" * 60)

    synsets = wn.synsets(word)

    for synset in synsets:
        print("Synset:", synset.name())
        print("Definition:", synset.definition())

        examples = synset.examples()

        if examples:
            print("Example:", examples[0])
        else:
            print("Example: No example available")

        print("-" * 50)

============================================================
WORD: car
============================================================
Synset: car.n.01
Definition: a motor vehicle with four wheels; usually propelled by an internal combustion engine
Example: he needs a car to get to work
--------------------------------------------------
Synset: car.n.02
Definition: a wheeled vehicle adapted to the rails of railroad
Example: three cars had jumped the rails
--------------------------------------------------
Synset: car.n.03
Definition: the compartment that is suspended from an airship and that carries personnel and the cargo and the power plant
Example: No example available
--------------------------------------------------
Synset: car.n.04
Definition: where passengers ride up and down
Example: the car was on the top floor
--------------------------------------------------
Synset: cable_car.n.01
Definition: a conveyance for passengers or freight on a cable railway
Example: they took a cable car to the top of the mountain
--------------------------------------------------

============================================================
WORD: bank
============================================================
Synset: bank.n.01
Definition: sloping land (especially the slope beside a body of water)
Example: they pulled the canoe up on the bank
--------------------------------------------------
Synset: depository_financial_institution.n.01
Definition: a financial institution that accepts deposits and channels the money into lending activities
Example: he cashed a check at the bank
--------------------------------------------------
Synset: bank.n.03
Definition: a long ridge or pile
Example: a huge bank of earth
--------------------------------------------------
Synset: bank.n.04
Definition: an arrangement of similar objects in a row or in tiers
Example: he operated a bank of switches
--------------------------------------------------
Synset: bank.n.05
Definition: a supply or stock held in reserve for future use (especially in emergencies)
Example: No example available
--------------------------------------------------
Synset: bank.n.06
Definition: the funds held by a gambling house or the dealer in some gambling games
Example: he tried to break the bank at Monte Carlo
--------------------------------------------------
Synset: bank.n.07
Definition: a slope in the turn of a road or track; the outside is higher than the inside in order to reduce the effects of centrifugal force
Example: No example available
--------------------------------------------------
Synset: savings_bank.n.02
Definition: a container (usually with a slot in the top) for keeping money at home
Example: the coin bank was empty
--------------------------------------------------
Synset: bank.n.09
Definition: a building in which the business of banking transacted
Example: the bank is on the corner of Nassau and Witherspoon
--------------------------------------------------
Synset: bank.n.10
Definition: a flight maneuver; aircraft tips laterally about its longitudinal axis (especially in turning)
Example: the plane went into a steep bank
--------------------------------------------------
Synset: bank.v.01
Definition: tip laterally
Example: the pilot had to bank the aircraft
--------------------------------------------------
Synset: bank.v.02
Definition: enclose with a bank
Example: bank roads
--------------------------------------------------
Synset: bank.v.03
Definition: do business with a bank or keep an account at a bank
Example: Where do you bank in this town?
--------------------------------------------------
Synset: bank.v.04
Definition: act as the banker in a game or in gambling
Example: No example available
--------------------------------------------------
Synset: bank.v.05
Definition: be in the banking business
Example: No example available
--------------------------------------------------
Synset: deposit.v.02
Definition: put into a bank account
Example: She deposits her paycheck every month
--------------------------------------------------
Synset: bank.v.07
Definition: cover with ashes so to control the rate of burning
Example: bank a fire
--------------------------------------------------
Synset: trust.v.01
Definition: have confidence or faith in
Example: We can trust in God
--------------------------------------------------

============================================================
WORD: bat
============================================================
Synset: bat.n.01
Definition: nocturnal mouselike mammal with forelimbs modified to form membranous wings and anatomical adaptations for echolocation by which they navigate
Example: No example available
--------------------------------------------------
Synset: bat.n.02
Definition: (baseball) a turn trying to get a hit
Example: he was at bat when it happened
--------------------------------------------------
Synset: squash_racket.n.01
Definition: a small racket with a long handle used for playing squash
Example: No example available
--------------------------------------------------
Synset: cricket_bat.n.01
Definition: the club used in playing cricket
Example: a cricket bat has a narrow handle and a broad flat end for hitting
--------------------------------------------------
Synset: bat.n.05
Definition: a club used for hitting a ball in various games
Example: No example available
--------------------------------------------------
Synset: bat.v.01
Definition: strike with, or as if with a baseball bat
Example: bat the ball
--------------------------------------------------
Synset: bat.v.02
Definition: wink briefly
Example: bat one's eyelids
--------------------------------------------------
Synset: bat.v.03
Definition: have a turn at bat
Example: Jones bats first, followed by Martinez
--------------------------------------------------
Synset: bat.v.04
Definition: use a bat
Example: Who's batting?
--------------------------------------------------
Synset: cream.v.02
Definition: beat thoroughly and conclusively in a competition or fight
Example: We licked the other team on Sunday!
--------------------------------------------------

============================================================
WORD: dog
============================================================
Synset: dog.n.01
Definition: a member of the genus Canis (probably descended from the common wolf) that has been domesticated by man since prehistoric times; occurs in many breeds
Example: the dog barked all night
--------------------------------------------------
Synset: frump.n.01
Definition: a dull unattractive unpleasant girl or woman
Example: she got a reputation as a frump
--------------------------------------------------
Synset: dog.n.03
Definition: informal term for a man
Example: you lucky dog
--------------------------------------------------
Synset: cad.n.01
Definition: someone who is morally reprehensible
Example: you dirty dog
--------------------------------------------------
Synset: frank.n.02
Definition: a smooth-textured sausage of minced beef or pork usually smoked; often served on a bread roll
Example: No example available
--------------------------------------------------
Synset: pawl.n.01
Definition: a hinged catch that fits into a notch of a ratchet to move a wheel forward or prevent it from moving backward
Example: No example available
--------------------------------------------------
Synset: andiron.n.01
Definition: metal supports for logs in a fireplace
Example: the andirons were too hot to touch
--------------------------------------------------
Synset: chase.v.01
Definition: go after with the intent to catch
Example: The policeman chased the mugger down the alley
--------------------------------------------------

============================================================
WORD: light
============================================================
Synset: light.n.01
Definition: (physics) electromagnetic radiation that can produce a visual sensation
Example: the light was filtered through a soft glass window
--------------------------------------------------
Synset: light.n.02
Definition: any device serving as a source of illumination
Example: he stopped the car and turned off the lights
--------------------------------------------------
Synset: light.n.03
Definition: a particular perspective or aspect of a situation
Example: although he saw it in a different light, he still did not understand
--------------------------------------------------
Synset: luminosity.n.01
Definition: the quality of being luminous; emitting or reflecting light
Example: its luminosity is measured relative to that of our sun
--------------------------------------------------
Synset: light.n.05
Definition: an illuminated area
Example: he stepped into the light
--------------------------------------------------
Synset: light.n.06
Definition: a condition of spiritual awareness; divine illumination
Example: follow God's light
--------------------------------------------------
Synset: light.n.07
Definition: the visual effect of illumination on objects or scenes as created in pictures
Example: he could paint the lightest light and the darkest dark
--------------------------------------------------
Synset: light.n.08
Definition: a person regarded very fondly
Example: the light of my life
--------------------------------------------------
Synset: light.n.09
Definition: having abundant light or illumination
Example: they played as long as it was light
--------------------------------------------------
Synset: light.n.10
Definition: mental understanding as an enlightening experience
Example: he finally saw the light
--------------------------------------------------
Synset: sparkle.n.01
Definition: merriment expressed by a brightness or gleam or animation of countenance
Example: he had a sparkle in his eye
--------------------------------------------------
Synset: light.n.12
Definition: public awareness
Example: it brought the scandal to light
--------------------------------------------------
Synset: inner_light.n.01
Definition: a divine presence believed by Quakers to enlighten and guide the soul
Example: No example available
--------------------------------------------------
Synset: light.n.14
Definition: a visual warning signal
Example: they saw the light of the beacon
--------------------------------------------------
Synset: lighter.n.02
Definition: a device for lighting or igniting fuel or charges or fires
Example: do you have a light?
--------------------------------------------------
Synset: light.v.01
Definition: make lighter or brighter
Example: This lamp lightens the room a bit
--------------------------------------------------
Synset: light_up.v.05
Definition: begin to smoke
Example: After the meal, some of the diners lit up
--------------------------------------------------
Synset: alight.v.01
Definition: to come to rest, settle
Example: Misfortune lighted upon him
--------------------------------------------------
Synset: ignite.v.01
Definition: cause to start burning; subject to fire or great heat
Example: Great heat can ignite almost any dry matter
--------------------------------------------------
Synset: fall.v.20
Definition: fall to somebody by assignment or lot
Example: The task fell to me
--------------------------------------------------
Synset: unhorse.v.01
Definition: alight from (a horse)
Example: No example available
--------------------------------------------------
Synset: light.a.01
Definition: of comparatively little physical weight or density
Example: a light load
--------------------------------------------------
Synset: light.a.02
Definition: (used of color) having a relatively small amount of coloring agent
Example: light blue
--------------------------------------------------
Synset: light.a.03
Definition: of the military or industry; using (or being) relatively small or light arms or equipment
Example: light infantry
--------------------------------------------------
Synset: light.a.04
Definition: not great in degree or quantity or number
Example: a light sentence
--------------------------------------------------
Synset: light.a.05
Definition: psychologically light; especially free from sadness or troubles
Example: a light heart
--------------------------------------------------
Synset: light.a.06
Definition: characterized by or emitting light
Example: a room that is light when the shutters are open
--------------------------------------------------
Synset: unaccented.s.02
Definition: (used of vowels or syllables) pronounced with little or no stress
Example: a syllable that ends in a short vowel is a light syllable
--------------------------------------------------
Synset: light.s.08
Definition: easily assimilated in the alimentary canal; not rich or heavily seasoned
Example: a light diet
--------------------------------------------------
Synset: light.s.09
Definition: (used of soil) loose and large-grained in consistency
Example: light soil
--------------------------------------------------
Synset: clean.s.03
Definition: (of sound or color) free from anything that dulls or dims
Example: efforts to obtain a clean bass in orchestral recordings
--------------------------------------------------
Synset: light.s.11
Definition: moving easily and quickly; nimble
Example: the dancer was light and graceful
--------------------------------------------------
Synset: light.s.12
Definition: demanding little effort; not burdensome
Example: light housework
--------------------------------------------------
Synset: light.a.13
Definition: of little intensity or power or force
Example: the light touch of her fingers
--------------------------------------------------
Synset: light.a.14
Definition: (physics, chemistry) not having atomic weight greater than average
Example: light water is ordinary water
--------------------------------------------------
Synset: faint.s.04
Definition: weak and likely to lose consciousness
Example: suddenly felt faint from the pain
--------------------------------------------------
Synset: light.s.16
Definition: very thin and insubstantial
Example: thin paper
--------------------------------------------------
Synset: abstemious.s.02
Definition: marked by temperance in indulgence
Example: abstemious with the use of adverbs
--------------------------------------------------
Synset: light.s.18
Definition: less than the correct or legal or full amount often deliberately so
Example: a light pound
--------------------------------------------------
Synset: light.s.19
Definition: having little importance
Example: losing his job was no light matter
--------------------------------------------------
Synset: light.s.20
Definition: intended primarily as entertainment; not serious or profound
Example: light verse
--------------------------------------------------
Synset: idle.s.04
Definition: silly or trivial
Example: idle pleasure
--------------------------------------------------
Synset: light.s.22
Definition: designed for ease of movement or to carry little weight
Example: light aircraft
--------------------------------------------------
Synset: light.s.23
Definition: having relatively few calories
Example: diet cola
--------------------------------------------------
Synset: light.s.24
Definition: (of sleep) easily disturbed
Example: in a light doze
--------------------------------------------------
Synset: easy.s.10
Definition: casual and unrestrained in sexual behavior
Example: her easy virtue
--------------------------------------------------
Synset: lightly.r.02
Definition: with few burdens
Example: experienced travellers travel light
--------------------------------------------------

============================================================
WORD: plant
============================================================
Synset: plant.n.01
Definition: buildings for carrying on industrial labor
Example: they built a large plant to manufacture automobiles
--------------------------------------------------
Synset: plant.n.02
Definition: (botany) a living organism lacking the power of locomotion
Example: No example available
--------------------------------------------------
Synset: plant.n.03
Definition: an actor situated in the audience whose acting is rehearsed but seems spontaneous to the audience
Example: No example available
--------------------------------------------------
Synset: plant.n.04
Definition: something planted secretly for discovery by another
Example: the police used a plant to trick the thieves
--------------------------------------------------
Synset: plant.v.01
Definition: put or set (seeds, seedlings, or plants) into the ground
Example: Let's plant flowers in the garden
--------------------------------------------------
Synset: implant.v.01
Definition: fix or set securely or deeply
Example: He planted a knee in the back of his opponent
--------------------------------------------------
Synset: establish.v.02
Definition: set up or lay the groundwork for
Example: establish a new department
--------------------------------------------------
Synset: plant.v.04
Definition: place into a river
Example: plant fish
--------------------------------------------------
Synset: plant.v.05
Definition: place something or someone in a certain position in order to secretly observe or deceive
Example: Plant a spy in Moscow
--------------------------------------------------
Synset: plant.v.06
Definition: put firmly in the mind
Example: Plant a thought in the students' minds
--------------------------------------------------

============================================================
WORD: book
============================================================
Synset: book.n.01
Definition: a written work or composition that has been published (printed on pages bound together)
Example: I am reading a good book on economics
--------------------------------------------------
Synset: book.n.02
Definition: physical objects consisting of a number of pages bound together
Example: he used a large book as a doorstop
--------------------------------------------------
Synset: record.n.05
Definition: a compilation of the known facts regarding something or someone
Example: Al Smith used to say, `Let's look at the record'
--------------------------------------------------
Synset: script.n.01
Definition: a written version of a play or other dramatic composition; used in preparing for a performance
Example: No example available
--------------------------------------------------
Synset: ledger.n.01
Definition: a record in which commercial accounts are recorded
Example: they got a subpoena to examine our books
--------------------------------------------------
Synset: book.n.06
Definition: a collection of playing cards satisfying the rules of a card game
Example: No example available
--------------------------------------------------
Synset: book.n.07
Definition: a collection of rules or prescribed standards on the basis of which decisions are made
Example: they run things by the book around here
--------------------------------------------------
Synset: koran.n.01
Definition: the sacred writings of Islam revealed by God to the prophet Muhammad during his life at Mecca and Medina
Example: No example available
--------------------------------------------------
Synset: bible.n.01
Definition: the sacred writings of the Christian religions
Example: he went to carry the Word to the heathen
--------------------------------------------------
Synset: book.n.10
Definition: a major division of a long written composition
Example: the book of Isaiah
--------------------------------------------------
Synset: book.n.11
Definition: a number of sheets (ticket or stamps etc.) bound together on one edge
Example: he bought a book of stamps
--------------------------------------------------
Synset: book.v.01
Definition: engage for a performance
Example: Her agent had booked her for several concerts in Tokyo
--------------------------------------------------

In [4]:
# Store WordNet information in a DataFrame

data = []

for word in words:
    synsets = wn.synsets(word)

    # Display first 3 synsets for each word
    for synset in synsets[:3]:
        data.append({
            "Word": word,
            "Synset": synset.name(),
            "Definition": synset.definition(),
            "Example": synset.examples()[0] if synset.examples() else "No example available"
        })

df_q1 = pd.DataFrame(data)

df_q1

,Word,Synset,Definition,Example
0,car,car.n.01,a motor vehicle with four wheels; usually prop...,he needs a car to get to work
1,car,car.n.02,a wheeled vehicle adapted to the rails of rail...,three cars had jumped the rails
2,car,car.n.03,the compartment that is suspended from an airs...,No example available
3,bank,bank.n.01,sloping land (especially the slope beside a bo...,they pulled the canoe up on the bank
4,bank,depository_financial_institution.n.01,a financial institution that accepts deposits ...,he cashed a check at the bank
5,bank,bank.n.03,a long ridge or pile,a huge bank of earth
6,bat,bat.n.01,nocturnal mouselike mammal with forelimbs modi...,No example available
7,bat,bat.n.02,(baseball) a turn trying to get a hit,he was at bat when it happened
8,bat,squash_racket.n.01,a small racket with a long handle used for pla...,No example available
9,dog,dog.n.01,a member of the genus Canis (probably descende...,the dog barked all night
10,dog,frump.n.01,a dull unattractive unpleasant girl or woman,she got a reputation as a frump
11,dog,dog.n.03,informal term for a man,you lucky dog
12,light,light.n.01,(physics) electromagnetic radiation that can p...,the light was filtered through a soft glass wi...
13,light,light.n.02,any device serving as a source of illumination,he stopped the car and turned off the lights
14,light,light.n.03,a particular perspective or aspect of a situation,"although he saw it in a different light, he st..."
15,plant,plant.n.01,buildings for carrying on industrial labor,they built a large plant to manufacture automo...
16,plant,plant.n.02,(botany) a living organism lacking the power o...,No example available
17,plant,plant.n.03,an actor situated in the audience whose acting...,No example available
18,book,book.n.01,a written work or composition that has been pu...,I am reading a good book on economics
19,book,book.n.02,physical objects consisting of a number of pag...,he used a large book as a doorstop
20,book,record.n.05,a compilation of the known facts regarding som...,"Al Smith used to say, `Let's look at the record'"
21,teacher,teacher.n.01,a person whose occupation is teaching,No example available
22,teacher,teacher.n.02,a personified abstraction that teaches,books were his teachers
23,student,student.n.01,a learner who is enrolled in an educational in...,No example available
24,student,scholar.n.01,a learned person (especially in the humanities...,No example available
25,computer,computer.n.01,a machine for performing calculations automati...,No example available
26,computer,calculator.n.01,an expert at calculation (or at operating calc...,No example available

In [5]:
# Find words having multiple synsets

print("Words with multiple meanings:\n")

for word in words:
    synsets = wn.synsets(word)

    if len(synsets) > 1:
        print(f"{word}: {len(synsets)} synsets")

        for synset in synsets[:3]:
            print(" -", synset.name(), ":", synset.definition())

        print()

Words with multiple meanings:

car: 5 synsets
 - car.n.01 : a motor vehicle with four wheels; usually propelled by an internal combustion engine
 - car.n.02 : a wheeled vehicle adapted to the rails of railroad
 - car.n.03 : the compartment that is suspended from an airship and that carries personnel and the cargo and the power plant

bank: 18 synsets
 - bank.n.01 : sloping land (especially the slope beside a body of water)
 - depository_financial_institution.n.01 : a financial institution that accepts deposits and channels the money into lending activities
 - bank.n.03 : a long ridge or pile

bat: 10 synsets
 - bat.n.01 : nocturnal mouselike mammal with forelimbs modified to form membranous wings and anatomical adaptations for echolocation by which they navigate
 - bat.n.02 : (baseball) a turn trying to get a hit
 - squash_racket.n.01 : a small racket with a long handle used for playing squash

dog: 8 synsets
 - dog.n.01 : a member of the genus Canis (probably descended from the common wolf) that has been domesticated by man since prehistoric times; occurs in many breeds
 - frump.n.01 : a dull unattractive unpleasant girl or woman
 - dog.n.03 : informal term for a man

light: 47 synsets
 - light.n.01 : (physics) electromagnetic radiation that can produce a visual sensation
 - light.n.02 : any device serving as a source of illumination
 - light.n.03 : a particular perspective or aspect of a situation

plant: 10 synsets
 - plant.n.01 : buildings for carrying on industrial labor
 - plant.n.02 : (botany) a living organism lacking the power of locomotion
 - plant.n.03 : an actor situated in the audience whose acting is rehearsed but seems spontaneous to the audience

book: 15 synsets
 - book.n.01 : a written work or composition that has been published (printed on pages bound together)
 - book.n.02 : physical objects consisting of a number of pages bound together
 - record.n.05 : a compilation of the known facts regarding something or someone

teacher: 2 synsets
 - teacher.n.01 : a person whose occupation is teaching
 - teacher.n.02 : a personified abstraction that teaches

student: 2 synsets
 - student.n.01 : a learner who is enrolled in an educational institution
 - scholar.n.01 : a learned person (especially in the humanities); someone who by long study has gained mastery in one or more disciplines

computer: 2 synsets
 - computer.n.01 : a machine for performing calculations automatically
 - calculator.n.01 : an expert at calculation (or at operating calculating machines)

In [6]:
# Select 10 nouns

nouns = [
    "dog",
    "cat",
    "car",
    "computer",
    "teacher",
    "student",
    "book",
    "tree",
    "bird",
    "house"
]

print("Selected nouns:")
print(nouns)

Selected nouns:
['dog', 'cat', 'car', 'computer', 'teacher', 'student', 'book', 'tree', 'bird', 'house']

In [7]:
# Find the first noun synset and its direct hypernym

hypernym_data = []

for word in nouns:
    synsets = wn.synsets(word, pos=wn.NOUN)

    if synsets:
        synset = synsets[0]

        hypernyms = synset.hypernyms()

        direct_hypernyms = [
            h.name() for h in hypernyms
        ]

        hypernym_data.append({
            "Word": word,
            "Synset": synset.name(),
            "Direct Hypernyms": ", ".join(direct_hypernyms)
            if direct_hypernyms else "None"
        })

df_hypernyms = pd.DataFrame(hypernym_data)

df_hypernyms

       Word         Synset                   Direct Hypernyms
0       dog       dog.n.01  domestic_animal.n.01, canine.n.02
1       cat       cat.n.01                        feline.n.01
2       car       car.n.01                 motor_vehicle.n.01
3  computer  computer.n.01                       machine.n.01
4   teacher   teacher.n.01                      educator.n.01
5   student   student.n.01                      enrollee.n.01
6      book      book.n.01                   publication.n.01
7      tree      tree.n.01                   woody_plant.n.01
8      bird      bird.n.01                    vertebrate.n.01
9     house     house.n.01       building.n.01, dwelling.n.01

In [8]:
# Function to trace hypernym hierarchy

def get_hypernym_chain(synset, levels=3):
    chain = []
    current = synset

    for level in range(levels):
        chain.append(current.name())

        hypernyms = current.hypernyms()

        if not hypernyms:
            break

        current = hypernyms[0]

    return " -> ".join(chain)


# Trace hierarchy for the selected nouns

hierarchy_data = []

for word in nouns:
    synsets = wn.synsets(word, pos=wn.NOUN)

    if synsets:
        synset = synsets[0]

        hierarchy = get_hypernym_chain(synset, levels=3)

        hierarchy_data.append({
            "Word": word,
            "Synset": synset.name(),
            "Hypernym Chain": hierarchy
        })

df_hierarchy = pd.DataFrame(hierarchy_data)

df_hierarchy

       Word         Synset                                     Hypernym Chain
0       dog       dog.n.01    dog.n.01 -> domestic_animal.n.01 -> animal.n.01
1       cat       cat.n.01          cat.n.01 -> feline.n.01 -> carnivore.n.01
2       car       car.n.01  car.n.01 -> motor_vehicle.n.01 -> self-propell...
3  computer  computer.n.01       computer.n.01 -> machine.n.01 -> device.n.01
4   teacher   teacher.n.01  teacher.n.01 -> educator.n.01 -> professional....
5   student   student.n.01       student.n.01 -> enrollee.n.01 -> person.n.01
6      book      book.n.01         book.n.01 -> publication.n.01 -> work.n.02
7      tree      tree.n.01  tree.n.01 -> woody_plant.n.01 -> vascular_plan...
8      bird      bird.n.01      bird.n.01 -> vertebrate.n.01 -> chordate.n.01
9     house     house.n.01      house.n.01 -> building.n.01 -> structure.n.01

In [9]:
# Select at least 8 word pairs

word_pairs = [
    ("car", "automobile"),
    ("dog", "cat"),
    ("dog", "animal"),
    ("dog", "computer"),
    ("car", "bus"),
    ("teacher", "student"),
    ("book", "magazine"),
    ("bird", "fish")
]

print("Word pairs:")
for pair in word_pairs:
    print(pair)

Word pairs:
('car', 'automobile')
('dog', 'cat')
('dog', 'animal')
('dog', 'computer')
('car', 'bus')
('teacher', 'student')
('book', 'magazine')
('bird', 'fish')

In [10]:
# Calculate WordNet Path Similarity

similarity_data = []

for word1, word2 in word_pairs:

    synsets1 = wn.synsets(word1, pos=wn.NOUN)
    synsets2 = wn.synsets(word2, pos=wn.NOUN)

    if synsets1 and synsets2:

        synset1 = synsets1[0]
        synset2 = synsets2[0]

        similarity = synset1.path_similarity(synset2)

        similarity_data.append({
            "Word 1": word1,
            "Word 2": word2,
            "Synset 1": synset1.name(),
            "Synset 2": synset2.name(),
            "Path Similarity": similarity
        })

df_similarity = pd.DataFrame(similarity_data)

df_similarity

    Word 1      Word 2      Synset 1       Synset 2  Path Similarity
0      car  automobile      car.n.01       car.n.01         1.000000
1      dog         cat      dog.n.01       cat.n.01         0.200000
2      dog      animal      dog.n.01    animal.n.01         0.333333
3      dog    computer      dog.n.01  computer.n.01         0.090909
4      car         bus      car.n.01       bus.n.01         0.125000
5  teacher     student  teacher.n.01   student.n.01         0.142857
6     book    magazine     book.n.01  magazine.n.01         0.333333
7     bird        fish     bird.n.01      fish.n.01         0.250000

In [11]:
# Rank word pairs according to similarity score

df_ranked = df_similarity.sort_values(
    by="Path Similarity",
    ascending=False
).reset_index(drop=True)

# Add rank
df_ranked.insert(
    0,
    "Rank",
    range(1, len(df_ranked) + 1)
)

df_ranked

   Rank   Word 1      Word 2      Synset 1       Synset 2  Path Similarity
0     1      car  automobile      car.n.01       car.n.01         1.000000
1     2      dog      animal      dog.n.01    animal.n.01         0.333333
2     3     book    magazine     book.n.01  magazine.n.01         0.333333
3     4     bird        fish     bird.n.01      fish.n.01         0.250000
4     5      dog         cat      dog.n.01       cat.n.01         0.200000
5     6  teacher     student  teacher.n.01   student.n.01         0.142857
6     7      car         bus      car.n.01       bus.n.01         0.125000
7     8      dog    computer      dog.n.01  computer.n.01         0.090909

In [12]:
# Homonyms with two different contextual meanings

sentences = [
    {
        "Word": "bank",
        "Sentence": "I deposited money in the bank.",
        "Meaning": "Financial institution",
        "Context Clue": "deposited money"
    },
    {
        "Word": "bank",
        "Sentence": "We sat on the bank of the river.",
        "Meaning": "Side of a river",
        "Context Clue": "river"
    },

    {
        "Word": "bat",
        "Sentence": "The player hit the ball with a bat.",
        "Meaning": "Sports equipment",
        "Context Clue": "player, ball"
    },
    {
        "Word": "bat",
        "Sentence": "A bat flew out of the cave.",
        "Meaning": "Flying mammal",
        "Context Clue": "flew, cave"
    },

    {
        "Word": "bark",
        "Sentence": "The dog began to bark loudly.",
        "Meaning": "Sound made by a dog",
        "Context Clue": "dog, loudly"
    },
    {
        "Word": "bark",
        "Sentence": "The bark of the tree was rough.",
        "Meaning": "Outer covering of a tree",
        "Context Clue": "tree, rough"
    },

    {
        "Word": "light",
        "Sentence": "Please turn on the light.",
        "Meaning": "Illumination",
        "Context Clue": "turn on"
    },
    {
        "Word": "light",
        "Sentence": "This bag is very light.",
        "Meaning": "Not heavy",
        "Context Clue": "bag, not heavy"
    },

    {
        "Word": "match",
        "Sentence": "India won the cricket match.",
        "Meaning": "Sports competition",
        "Context Clue": "cricket, won"
    },
    {
        "Word": "match",
        "Sentence": "He lit a match to start the fire.",
        "Meaning": "Small stick used to produce fire",
        "Context Clue": "lit, fire"
    }
]

df_context = pd.DataFrame(sentences)

df_context

,Word,Sentence,Meaning,Context Clue
0,bank,I deposited money in the bank.,Financial institution,deposited money
1,bank,We sat on the bank of the river.,Side of a river,river
2,bat,The player hit the ball with a bat.,Sports equipment,"player, ball"
3,bat,A bat flew out of the cave.,Flying mammal,"flew, cave"
4,bark,The dog began to bark loudly.,Sound made by a dog,"dog, loudly"
5,bark,The bark of the tree was rough.,Outer covering of a tree,"tree, rough"
6,light,Please turn on the light.,Illumination,turn on
7,light,This bag is very light.,Not heavy,"bag, not heavy"
8,match,India won the cricket match.,Sports competition,"cricket, won"
9,match,He lit a match to start the fire.,Small stick used to produce fire,"lit, fire"

In [13]:
# Display different WordNet synsets for each homonym

homonyms = ["bank", "bat", "bark", "light", "match"]

for word in homonyms:
    print("\n" + "=" * 60)
    print("HOMONYM:", word)
    print("=" * 60)

    synsets = wn.synsets(word)

    for synset in synsets[:6]:
        print("Synset:", synset.name())
        print("Definition:", synset.definition())
        print("-" * 40)

============================================================
HOMONYM: bank
============================================================
Synset: bank.n.01
Definition: sloping land (especially the slope beside a body of water)
----------------------------------------
Synset: depository_financial_institution.n.01
Definition: a financial institution that accepts deposits and channels the money into lending activities
----------------------------------------
Synset: bank.n.03
Definition: a long ridge or pile
----------------------------------------
Synset: bank.n.04
Definition: an arrangement of similar objects in a row or in tiers
----------------------------------------
Synset: bank.n.05
Definition: a supply or stock held in reserve for future use (especially in emergencies)
----------------------------------------
Synset: bank.n.06
Definition: the funds held by a gambling house or the dealer in some gambling games
----------------------------------------

============================================================
HOMONYM: bat
============================================================
Synset: bat.n.01
Definition: nocturnal mouselike mammal with forelimbs modified to form membranous wings and anatomical adaptations for echolocation by which they navigate
----------------------------------------
Synset: bat.n.02
Definition: (baseball) a turn trying to get a hit
----------------------------------------
Synset: squash_racket.n.01
Definition: a small racket with a long handle used for playing squash
----------------------------------------
Synset: cricket_bat.n.01
Definition: the club used in playing cricket
----------------------------------------
Synset: bat.n.05
Definition: a club used for hitting a ball in various games
----------------------------------------
Synset: bat.v.01
Definition: strike with, or as if with a baseball bat
----------------------------------------

============================================================
HOMONYM: bark
============================================================
Synset: bark.n.01
Definition: tough protective covering of the woody stems and roots of trees and other woody plants
----------------------------------------
Synset: bark.n.02
Definition: a noise resembling the bark of a dog
----------------------------------------
Synset: bark.n.03
Definition: a sailing ship with 3 (or more) masts
----------------------------------------
Synset: bark.n.04
Definition: the sound made by a dog
----------------------------------------
Synset: bark.v.01
Definition: speak in an unfriendly tone
----------------------------------------
Synset: bark.v.02
Definition: cover with bark
----------------------------------------

============================================================
HOMONYM: light
============================================================
Synset: light.n.01
Definition: (physics) electromagnetic radiation that can produce a visual sensation
----------------------------------------
Synset: light.n.02
Definition: any device serving as a source of illumination
----------------------------------------
Synset: light.n.03
Definition: a particular perspective or aspect of a situation
----------------------------------------
Synset: luminosity.n.01
Definition: the quality of being luminous; emitting or reflecting light
----------------------------------------
Synset: light.n.05
Definition: an illuminated area
----------------------------------------
Synset: light.n.06
Definition: a condition of spiritual awareness; divine illumination
----------------------------------------

============================================================
HOMONYM: match
============================================================
Synset: match.n.01
Definition: lighter consisting of a thin piece of wood or cardboard tipped with combustible chemical; ignites with friction
----------------------------------------
Synset: match.n.02
Definition: a formal contest in which two or more persons or teams compete
----------------------------------------
Synset: match.n.03
Definition: a burning piece of wood or cardboard
----------------------------------------
Synset: match.n.04
Definition: an exact duplicate
----------------------------------------
Synset: match.n.05
Definition: the score needed to win a match
----------------------------------------
Synset: catch.n.03
Definition: a person regarded as a good matrimonial prospect
----------------------------------------

In [14]:
# Final table containing word, sentence, intended meaning and context clue

final_table = df_context[
    ["Word", "Sentence", "Meaning", "Context Clue"]
]

final_table

,Word,Sentence,Meaning,Context Clue
0,bank,I deposited money in the bank.,Financial institution,deposited money
1,bank,We sat on the bank of the river.,Side of a river,river
2,bat,The player hit the ball with a bat.,Sports equipment,"player, ball"
3,bat,A bat flew out of the cave.,Flying mammal,"flew, cave"
4,bark,The dog began to bark loudly.,Sound made by a dog,"dog, loudly"
5,bark,The bark of the tree was rough.,Outer covering of a tree,"tree, rough"
6,light,Please turn on the light.,Illumination,turn on
7,light,This bag is very light.,Not heavy,"bag, not heavy"
8,match,India won the cricket match.,Sports competition,"cricket, won"
9,match,He lit a match to start the fire.,Small stick used to produce fire,"lit, fire"